/** ----- NPM PACKAGE IMPORTS -----**/
import React from "react";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faShoppingCart, faDollarSign, faUser, faBell} from "@fortawesome/free-solid-svg-icons";

/** ----- COMPONENT IMPORTS -----**/

/** ----- CSS/STYLING IMPORTS -----**/
import "../../resources/static/css/staff.css";

/**
 * This JS file contains all code related to the rendering of the 'Staff' perspective.
 *
 * Any components you wish to create related to this perspective should be developed within
 * this file.
 */

export class Staff extends React.Component {
    render() {
        return (
            <div className={"page staff-page"}>
                <StaffLanding orders={this.props.orders}
                              orderAttributes={this.props.orderAttributes}
                              diningSessions={this.props.diningSessions}
                              diningSessionsAttributes={this.props.diningSessionAttributes}
                              selectedView={this.props.selectedView}/>
            </div>
        )
    }
}

class StaffLanding extends React.Component {
    constructor(props) {
        super(props);
        this.handleClickOrders = this.handleClickOrders.bind(this);
        this.handleClickRequests = this.handleClickRequests.bind(this);
    }

    // Method called when attempting to navigate to the 'Staff Requests' page
    handleClickRequests(){
        this.props.history.push({
            pathname: '/staff-requests',
            state: {}
        })
    }

    // Method called when attempting to navigate to the 'Staff Orders' page
    handleClickOrders(){
        this.props.history.push({
            pathname: '/staff-orders',
            state: {}
        })
    }

    render() {
        return (
            <div>
                <title>Staff Landing Page</title>
                <div id = "staff-wrapper">
                    <header className="staff-frontpage">
                        <a href="#" className="staff-logo">
                            <img src="./img/logo.png" alt="Home"/>
                        </a>
                    </header>
                    {/*<FontAwesomeIcon icon={faBell} className="landing-page-header-button-icons"/>*/}
                </div>
                <div className="staff-navigation">
                    <div className="staff-overlay">
                        <div className="staff-nav-btn-wrapper">
                            <button className="staff-nav-btn">Request</button>
                        </div>
                        <div className="staff-nav-btn-wrapper">
                            <button className="staff-nav-btn">All Orders</button>
                        </div>
                    </div>
                </div>
            </div>


        )
    }
}


/**
 * This component should contain the 'page' for the staff member to view all the current customer requests,
 * either bill or service requests.
 *
 * See 'Customer-Menu' component in Customer.js for an example of how to navigate to this page and connect it
 * to the Staff component above.
 */
export class StaffRequests extends React.Component {
    constructor(props){
        super(props);
    }

    render() {
        return(
          <div>

          </div>
        );
    }
}


/**
 * This component should contain the 'page' for the staff member to view all the current orders,
 * generated by customers.
 */
export class StaffOrders extends React.Component {
    constructor(props){
        super(props);
    }

    render() {
        return(
            <div>

            </div>
        );
    }

}